#!/bin/bash

rmmod mac802154_hwsim
rmmod mac802154
rmmod ieee802154_6lowpan
rmmod ieee802154
modprobe mac802154_hwsim
wpan-hwsim add
wpan-hwsim add
wpan-hwsim add
wpan-hwsim add

# BUILD TOPOLOGY
wpan-hwsim edge add 0 2
wpan-hwsim edge add 2 0

wpan-hwsim edge add 1 3
wpan-hwsim edge add 3 1

wpan-hwsim edge add 4 3
wpan-hwsim edge add 3 4

wpan-hwsim edge add 2 3
wpan-hwsim edge add 3 2

wpan-hwsim edge add 4 1
wpan-hwsim edge add 1 4

wpan-hwsim edge add 4 5
wpan-hwsim edge add 5 4

for i in `seq 0 5`
do
	ip netns add ns$i
	iwpan phy phy$i set netns name ns$i
	ip netns exec ns$i iwpan dev wpan$i set pan_id 0xbeef
	ip netns exec ns$i ip link add link wpan$i name lowpan$i type lowpan
	ip netns exec ns$i ip link set wpan$i up
	ip netns exec ns$i ip link set lowpan$i up
done
